### ISSUE TITLE
Maintain chronological order in Tidal playlist

### ISSUE THREAD

**Issue by aarohmankad** [timrae/spotify_to_tidal#10]
Current Behavior: Syncing a playlist correctly syncs the tracks to a new playlist. However, when sorting the Tidal playlist, we actually get the inverse order as the Spotify playlist. For example, Tidal's playlist has to be in descending date order to match Spotify's ascending date order.

Desired Behavior: When sorting by the "Date Added" column, the Spotify and Tidal playlists should have an identical order.

Fix: Reverse the Tidal tracks before appending them to the playlist.

**Comment by timrae** [comment]
This is a tidal issue not a problem with the script. When you choose date added as the sort field it's using descending order instead of ascending order. If you want to be able to choose the sort order then you should request the feature from tidal.

**Comment by aarohmankad** [comment]
@timrae I think there's a misunderstanding here. Tidal lets me sort in both orders, but the order that we add the songs into the playlist swaps the meaning of ascending/descending. Let's assume my Spotify playlist looks like this, sorted in reverse-chronological order:

* B (added 1 day ago)
* C (added 1 week ago)
* D (added 1 year ago)

This syncs into my Tidal playlist in (B, C, D) order. Now I'll sort my Tidal playlist in reverse chronological order. My expectation is that it matches the Spotify order. However, I get:

* D (Added to Tidal playlist last, hence "most recent")
* C
* B (Added to Tidal playlist 1st, hence "longest time" ago)

I could flip my sorting to get the correct order: (B, C, D). However, when I add Song A, it gets punted to the bottom of the playlist instead of the top. In the Spotify sort order, if I add Song A I would have the desired order (A, B, C, D). In Tidal, I now get (B, C, D, A)

Let me know if that helps illustrate the problem!

**Comment by timrae** [comment]
> This syncs into my Tidal playlist in (B, C, D) order. 

Hmm I'm not sure where you're getting this idea from...  It syncs your playlist in 'custom order', which is generally chronological order if you haven't done any manual reordering of the playlist. So unless you've specifically gone and manually reordered them to be in that order, then it'll be synced to tidal as D, C, B.

I don't make any attempt to maintain the order it was added between Spotify and Tidal. Your proposed patch doesn't add this feature either, it just reverses the custom order, which breaks the main use case.
