### ISSUE TITLE
Not all playlist are sync

### ISSUE THREAD

**Issue by amibumping** [timrae/spotify_to_tidal#17]
Hi, I tried today the script, and after finish and check there were no errors I see on my tidal account, only the playlist created by me are sync, but not others playlist saved on my account.

Is there an error, or something I have to config?

Thank you anyway!

**Comment by timrae** [comment]
Only your own playlists are synced currently, could add an option for this
but don't have the feature now. You can manually sync other playlists if
you need to though by specifying the uri.

**Comment by amibumping** [comment]
It would be a nice add.

I've done it specifying the URI, and it went perfect.

Thank you!
