### ISSUE TITLE
Failed to get all playlists.

### ISSUE THREAD

**Issue by 321098123** [timrae/spotify_to_tidal#18]
![image](https://user-images.githubusercontent.com/74374885/222805551-2d7d0dbc-d761-4044-8294-5bacf2f8fb6f.png)

I tried to get all the playlists, but no text appears and it ends. 
I import normally if I use the uri option. 
Please help me get all the playlists.

**Comment by timrae** [comment]
How long did you wait for it? I think it can take a few minutes before you see anything

**Comment by 321098123** [comment]
Wait 3 to 5 seconds and exit immediately

**Comment by timrae** [comment]
Hmm that's weird, I ran the script yesterday and didn't have any issues.

Maybe it could be an authentication issue.  Can you try deleting any hidden
files (I.e. files with .* names) which should force a sign in again, which
might fix the problem. Also check that the account you sign into is the
correct one and contains some user playlists (i.e. playlists which you
created yourself. Other people's playlists which you follow won't be
automatically synced currently).

**Comment by 321098123** [comment]
I tried many things, but they didn't work out. What's unusual is that the uri option works, 
but only the entire playlist doesn't work. 
It must be my account problem (passing from Korea to Argentina). 
Thank you for your answer.

**Comment by O-Karadan** [comment]
Hey there,
I cannot import. Webbrowser opens for auth (both, with --uri an without). Deleted .* Files. Nothing changed. 
Always shows:
![err](https://user-images.githubusercontent.com/75649513/227772237-2bef9a6d-c9b4-4c1f-bb82-826c18f226cd.png)

**Comment by timrae** [comment]
See upstream issue here and associated workaround. I'll update this repo when it gets fixed upstream, for now you'll need to patch your tidalapi version locally (e.g. by commenting out the offending line)

https://github.com/tamland/python-tidal/issues/129

**Comment by tehkillerbee** [comment]
@24802 This has now finally been fixed in the tidalapi. We will update the PyPI release ASAP.

**Comment by designingEmergence** [comment]
I had the same issue as @24802 and did some digging to figure it out. Turns out that my userid was just made up of numbers so when trying to match ids of my spotify username with what was being returned by the API, the type mismatch caused the condition to return false. Simply putting my username in the config in quotes fixed the problem.

**Comment by RobinHirst11** [comment]
So can we close this error please, or mark it as resolved?

**Comment by tehkillerbee** [comment]
Yes, I believe this is fixed when using latest tidalapi
