### ISSUE TITLE
How to know if it is working?

### ISSUE THREAD

**Issue by matiasramirez1601** [timrae/spotify_to_tidal#24]
I give python3 sync.py (in my case with python sync.py it works)
It opens the verification windows for spotify and Tidal but when I open tidal after verifying the code, the subscription window pops up and I am tidal free user.
The console shows this message Login with the webbrowser: link.tidal.com/(berification code) but then nothing else is shown.
https://i.postimg.cc/XJ3m96Nt/Captura-de-pantalla-2023-06-07-122721.png

**Comment by RobinHirst11** [comment]
do you have python installed?
![image](https://github.com/timrae/spotify_to_tidal/assets/147210082/21d03777-8fe0-4e64-a1d6-b5f0c836f8e0)



if you do, try make a virtual environment
```python3 -m venv myenv```
```source myenv/bin/activate```

you said you verified the code, after you do so, mind just closing the pop up/closing the window and sending another screenshot of your terminal?

**Comment by timrae** [comment]
I've added a few more logging messages recently, so you should expect to see the following on running the script:

```
Opening Spotify session
Opening Tidal session
Loading Spotify playlists:   0%|
```
