### ISSUE TITLE
pyyaml==6.0 fails to install on Python 3.12

### ISSUE THREAD

**Issue by xtarlit** [timrae/spotify_to_tidal#32]
Fixed this by simply changing it to pyyaml==6.0.1 in requirements.txt but if I'm honest I have no clue what I'm doing with Python, so I've no clue if that's the latest version or anything like that.

**Comment by timrae** [comment]
Thanks for reporting, we've updated the build system a bit and now using the [compatible-release](https://packaging.python.org/en/latest/specifications/version-specifiers/#compatible-release) syntax so this should not be an issue any longer.
