### ISSUE TITLE
tidal credentials ?

### ISSUE THREAD

**Issue by zedug** [timrae/spotify_to_tidal#4]
had a tidal login problem but it turns out that Tidal changed the secret values so tidalapi barfed.
I ended up hardcoding the secrets from [here](https://github.com/yaronzz/Tidal-Media-Downloader/issues/797) in tidalapi\__init__.py and bob is my uncle

**Comment by zedug** [comment]
this is really a tidalapi issue

**Comment by steakscience** [comment]
@zedug This is really helpful!

Where can I find the init.py?

**Comment by steakscience** [comment]
Interesting part is this repo targets tidalapi 0.6.8
So I updated to tidalapi 0.6.9 which updates the secret values

However, this did not fix it

**Comment by zedug** [comment]
yes the values changed very recently so tidalapi 0.6.9 is not up to date
_ _ init.py _ _ is in the tidalapi package directory, wherever you installed it

**Comment by steakscience** [comment]
@zedug Gotchu, what should this part be?

I tried values from the issue you linked, but I'm not sure I put them in the right format:

```py
self.client_id = list((base64.b64decode("b4x3gVV8WXlEhGt5eIhkgWQuelsrhzmGRn5wgXZ/R1gy"
                                                "NERseEVDTnRGRU1CeGlwVTBsQmZyYnE2MD0=").decode('ISO-8859-1')))
        if save:
            token2.decode('ISO-8859-1').encode('utf-16')
            self.client_id = [x.encode('ISO-8859-1') for x in self.client_id]
        for word in token2:
            self.client_id.remove(word)
        self.client_id = "".join(self.client_id)
        # self.client_secret = self.client_id
        # self.client_id = self.api_token
        self.client_secret = "7m7Ap0JC9j1cOM3n"
        self.client_id = "owUYDkxddz+9FpvGX24DlxECNtFEMBxipU0lBfrbq60="
```

**Comment by timrae** [comment]
Oh I just bumped the version to 0.6.9, I thought it included the change to the client secret but you're right that version predates the most recent change

**Comment by zedug** [comment]
the values are found specifically in AminurAlam's comment https://github.com/yaronzz/Tidal-Media-Downloader/issues/797#issuecomment-1015617361

my changes are below, indeed at line 120, I used single quotes

```
#        self.client_secret = self.client_id
#        self.client_id = self.api_token
        self.client_secret = 'vRAdA108tlvkJpTsGZS8rGZ7xTlbJ0qaZ2K9saEzsgY='
        self.client_id = '7m7Ap0JC9j1cOM3n'
```

**Comment by timrae** [comment]
Fixed in the latest version of tidalapi, which I've added to the requirements file now
