### ISSUE TITLE
Repeated sync feature

### ISSUE THREAD

**Issue by c0ball** [timrae/spotify_to_tidal#54]
Hey,
as this application is currently focused on migrating a Spotify library to Tidal, I would like to know if there are any plans on expanding the application to support features for repeated syncs as for example:

- Add multiple one to one mappings, so that you can specify multiple playlist you want to sync
- Add only tracks to a tidal playlist, which have not been added before

If nobody is currently developing these functions, I could take on this task if you want to.

**Comment by timrae** [comment]
Hi if I understood you correctly, it already has these features, in fact they are the primary purpose of the script

**Comment by c0ball** [comment]
Oh yeah you are right, I misunderstood the configuration yaml😬

**Comment by timrae** [comment]
Thanks, I added a small note to the readme to make it more clear
