### ISSUE TITLE
Enhancement: Synchronization scheduler

### ISSUE THREAD

**Issue by c0ball** [timrae/spotify_to_tidal#58]
Wouldn't it be helpful for the users, which run this script on a regular basis, to add some kind of scheduler so that the synchronization automatically gets run every day or week.

**Comment by timrae** [comment]
I think this is beyond the scope of this project, as the operating system offers this functionality already (for example chrontabs on Linux/Mac/WSL). However feel free to add some documentation on how to achieve this.
