### ISSUE TITLE
Umlauts

### ISSUE THREAD

**Issue by JW5PX** [timrae/spotify_to_tidal#6]
It seems songs with umlaut containing (Ä, Ö, Å) names are excluded in import.

For example CMX - Yöllisiä
https://open.spotify.com/track/0Kw4DHSo7hlZW6FHokdtdv?si=53f47d93724d464d

Maybe replace would work
Ä, Å--> A
Ö --> O

**Comment by JW5PX** [comment]
I tried to add replace in def simple(input_string) but no luck. Still could not find the track.

**Comment by JW5PX** [comment]
This seemed to do the trick on sync.py line 22 

`    #return unidecode(input_string).split('-')[0].strip().split('(')[0].strip().split('[')[0].strip()`
`    return input_string.split('-')[0].strip().split('(')[0].strip().split('[')[0].strip()`

**Comment by timrae** [comment]
Thanks I had already fixed this locally but hadn't pushed yet. Should be working now.
