### ISSUE TITLE
Readme needs updating

### ISSUE THREAD

**Issue by SturdyStubs** [timrae/spotify_to_tidal#71]
Readme is very inaccurate. Some features no longer work such as sync-favorites which isn't even listed in the help section.

**Comment by timrae** [comment]
The readme is up to date AFAIK, sync favorites should be working, and is listed in the help section. It sounds like you haven't installed properly. Please make sure you checked out the latest version and follow the installation instructions again, and open a new issue with exact repro steps for any broken functionality.

```
usage: spotify_to_tidal [-h] [--config CONFIG] [--uri URI] [--sync-favorites | --no-sync-favorites]

options:
  -h, --help            show this help message and exit
  --config CONFIG       location of the config file
  --uri URI             synchronize a specific URI instead of the one in the config
  --sync-favorites, --no-sync-favorites
                        synchronize the favorites
```
