### ISSUE TITLE
zsh command not found

### ISSUE THREAD

**Issue by JustVerhagen** [timrae/spotify_to_tidal#76]
When I run the command, it says "zsh: command not found: spotify_to_tidal"

maybe it is just me but idk pls help

**Comment by timrae** [comment]
Sounds like you didn't follow the instructions in the readme, specifically at the top of the readme:

```bash
python3 -m pip install -e .
```

**Comment by tiagorazoyo** [comment]
@JustVerhagen

You could try `python3 -m spotify_to_tidal` on the root folder.

**Comment by hanshenrik** [comment]
I ran `python3 -m pip install -e .` first and got the same error when trying to run `spotify_to_tidal` in a `zsh` shell. Running `python3 -m spotify_to_tidal` worked ✌️
