### ISSUE TITLE
can't open file '\\spotify_to_tidal\\spotify_to_tidal': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by niss1m** [timrae/spotify_to_tidal#82]
tried fixing the error by moving '**spotify_to_tidal**' outside of '**src**' to **main folder** now I get a new error:

> **python3 spotify_to_tidal**

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\PC\Documents\development\spotify_to_tidal\spotify_to_tidal\__main__.py", line 5, in <module>
    from . import sync as _sync
ImportError: attempted relative import with no known parent package
```

**Comment by niss1m** [comment]
using latest release downloaded from releases

**Comment by timrae** [comment]
Hi, don't move the files out of the source folder, and do run the install command from the [readme](https://github.com/spotify2tidal/spotify_to_tidal/blob/main/readme.md)

**Comment by timrae** [comment]
Usually to run the script after installation you should just be able to run `spotify_to_tidal` from the directory where you have the config file. If there's something wrong with your python environment variables then you could try this instead:

```bash
python3 -m spotify_to_tidal
```

**Comment by niss1m** [comment]
yeah my bad, -m fixed it for me. thanks a lot!
