### ISSUE TITLE
Hangs at "Opening Spotify session"

### ISSUE THREAD

**Issue by emaniloff** [timrae/spotify_to_tidal#87]
I have a premium spotify subscription, i entered the client id and access key and username into the config.yml and when I run spotify_to_tidal it shows Opening Spotify session and just hangs there....any ideas how to fix this?  TIA

**Comment by timrae** [comment]
Usually a browser window would pop up that lets you authenticate. Are you on headless server by chance?

**Comment by timrae** [comment]
Try this and let me know:
https://github.com/spotify2tidal/spotify_to_tidal/pull/88
