### ISSUE TITLE
Cannot sync favourite tracks list

### ISSUE THREAD

**Issue by dgiglio** [timrae/spotify_to_tidal#9]
Hi,
This is more a request than a bug warn, by the way:
if I submit the favourite tracks list url (https://open.spotify.com/collection/tracks) the script cannot manage it.
Best regards

**Comment by danielengels** [comment]
would be a great addition!

**Comment by timrae** [comment]
If anyone is interested in implementing this feature, please let me know here before you start working on it and we can discuss what is the best approach to solving this problem. For example I would strongly recommend that we split up the existing `sync_playlist()` function into the parts that are common for both ordinary playlists and favourite tracks (e.g. something like `sync_tracks()`), and the rest which is specific to playlists. Then add a new function `sync_favourites()` which implements only the favourite specific logic, and calls the common function. I would like to avoid having a lot of duplicated code.

**Comment by c0ball** [comment]
If it is OK, then I would like to implement this feature. I have already created a first version that can synchronize the Spotify favorites with a Tidal playlist.

**Comment by timrae** [comment]
@c0ball yes please that would be great, could you please share your prototype so we can give early feedback on the approach you've taken? Either post a link to the branch to here, or open up a WIP pull request

**Comment by c0ball** [comment]
I provided my first implementation in #55

**Comment by c0ball** [comment]
So, I have updated this #55 to integrate your feedback.
The favorites syncing is now enabled by default and can be disabled with the `--disable-favorites-sync` arg.
I refactored `sync_playlist` to a more generic `sync_tracks` function and moved the playlist and favorites specific logic into wrapper functions. I also created a generic `_fetch_all_from_spotify_in_chunks` to remove the redundant parts in `get_tracks_from_spotify_playlist` and `get_tracks_from_spotify_favorites`. I am currently trying to figure out why the order of the list of old tracks and new tracks changes when syncing favorites, which would resolve the issue that on every sync the favorites playlist gets cleared before updating.

**Comment by c0ball** [comment]
Yeah, I think I found the issue and now only the new items get added to the tidal favorites :)

**Comment by timrae** [comment]
I did some additional work based off @c0ball's branch on #63 and we just got that merged into `main` 💦 
Please test it and let us know any feedback

**Comment by timrae** [comment]
@c0ball if you are interested in doing some more work on this, #67 would be a great way to finish off this feature

**Comment by c0ball** [comment]
> @c0ball if you are interested in doing some more work on this, #67 would be a great way to finish off this feature

I can look into this, but I don't know when I'll have time for it. Maybe at the weekend.

**Comment by julence** [comment]
@c0ball bump hehe please whenever u can would be awesome. thanks 4 all

**Comment by c0ball** [comment]
I've implemented albums and artists syncing in #92
