### ISSUE TITLE
Cannot sync playlists made by Spotify?

### ISSUE THREAD

**Issue by kalpik** [timrae/spotify_to_tidal#93]
Does anyone else also have this issue where the playlists created by spotify themselves are not syncable anymore?

It errors out with:

spotify_to_tidal
Opening Spotify session
Opening Tidal session
HTTP Error for GET to https://api.spotify.com/v1/playlists/37i9dQZF1DXaXB8fQg7xif with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 404 due to Resource not found
Error getting Spotify playlist 37i9dQZF1DXaXB8fQg7xif

And indeed if you try out the API reference with the same playlist ID, it returns 404: https://developer.spotify.com/documentation/web-api/reference/get-playlist

**Comment by mjanonis** [comment]
https://github.com/spotipy-dev/spotipy/issues/1172

From https://developer.spotify.com/blog/2024-11-27-changes-to-the-web-api
> Effective today, new Web API use cases will no longer be able to access or use the following endpoints and functionality in their third-party applications. Applications with existing extended mode Web API access that were relying on these endpoints remain unaffected by this change.
    [SNIP]
    **Algorithmic and Spotify-owned editorial playlists**
